In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("/Users/victoriacano/Desktop/individual_project/data/raw/Phase1.csv", encoding="latin-1", low_memory=False, index_col=False)
df2 = pd.read_csv("/Users/victoriacano/Desktop/individual_project/data/raw/Phase2.csv", encoding="latin-1", low_memory=False, index_col=False)
df3 = pd.read_csv("/Users/victoriacano/Desktop/individual_project/data/raw/Phase3.csv", encoding="latin-1", low_memory=False, index_col=False)
df4 = pd.read_csv("/Users/victoriacano/Desktop/individual_project/data/raw/Phase4.csv", encoding="latin-1", low_memory=False, index_col=False)
df5 = pd.read_csv("/Users/victoriacano/Desktop/individual_project/data/raw/Phase5.csv", encoding="latin-1", low_memory=False, index_col=False)
df6 = pd.read_csv("/Users/victoriacano/Desktop/individual_project/data/raw/Phase6.csv", encoding="latin-1", low_memory=False, index_col=False)

In [3]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 65909 entries, 0 to 65908
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   typeCode                  65909 non-null  str
 1   freqCode                  65909 non-null  str
 2   refPeriodId               65909 non-null  int64
 3   refYear                   65909 non-null  int64
 4   refMonth                  65909 non-null  int64
 5   period                    65909 non-null  int64
 6   reporterCode              65909 non-null  int64
 7   reporterISO               65909 non-null  str
 8   reporterDesc              65909 non-null  str
 9   flowCode                  65909 non-null  str
 10  flowDesc                  65909 non-null  str
 11  partnerCode               65909 non-null  int64
 12  partnerISO                65909 non-null  str
 13  partnerDesc               65909 non-null  str
 14  partner2Code              65909 non-null  int64
 15  partner2ISO               65909 non-null  str
 16  partner2Desc              65909 non-null  str
 17  classificationCode        65909 non-null  str
 18  classificationSearchCode  65909 non-null  str
 19  isOriginalClassification  65909 non-null  bool
 20  cmdCode                   65909 non-null  int64
 21  cmdDesc                   65909 non-null  str
 22  aggrLevel                 65909 non-null  int64
 23  isLeaf                    65909 non-null  bool
 24  customsCode               65909 non-null  str
 25  customsDesc               65909 non-null  str
 26  mosCode                   65909 non-null  int64
 27  motCode                   65909 non-null  int64
 28  motDesc                   65909 non-null  str
 29  qtyUnitCode               65909 non-null  int64
 30  qtyUnitAbbr               44233 non-null  str
 31  qty                       52299 non-null  float64
 32  isQtyEstimated            65909 non-null  bool
 33  altQtyUnitCode            65909 non-null  int64
 34  altQtyUnitAbbr            771 non-null    str
 35  altQty                    6058 non-null   float64
 36  isAltQtyEstimated         65909 non-null  bool
 37  netWgt                    48818 non-null  float64
 38  isNetWgtEstimated         65909 non-null  bool
 39  grossWgt                  6058 non-null   float64
 40  isGrossWgtEstimated       65909 non-null  bool
 41  cifvalue                  34442 non-null  float64
 42  fobvalue                  36781 non-null  float64
 43  primaryValue              65909 non-null  float64
 44  legacyEstimationFlag      65909 non-null  int64
 45  isReported                65909 non-null  bool
 46  isAggregate               65909 non-null  bool
dtypes: bool(8), float64(7), int64(14), str(18)
memory usage: 20.1 MB

In [4]:
df1["motCode"].value_counts()

motCode
0       62742
1000     1327
3200      644
2100      463
9200      332
9900      238
3100       94
2200       38
9300       29
9100        2
Name: count, dtype: int64

In [5]:
df2

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20010101,2001,52,2001,8,ALB,Albania,M,...,10186.0,False,NaN,False,27854.0,NaN,27854.0,0,False,False
1,C,A,20010101,2001,52,2001,8,ALB,Albania,M,...,4.0,False,NaN,False,335.0,NaN,335.0,0,False,False
2,C,A,20010101,2001,52,2001,8,ALB,Albania,M,...,9409.0,False,NaN,False,22304.0,NaN,22304.0,0,False,False
3,C,A,20010101,2001,52,2001,8,ALB,Albania,M,...,86.0,False,NaN,False,1377.0,NaN,1377.0,0,False,False
4,C,A,20010101,2001,52,2001,8,ALB,Albania,M,...,685.0,False,NaN,False,884.0,NaN,884.0,0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94717,C,A,20080101,2008,52,2008,792,TUR,Türkiye,X,...,5196.0,False,0.0,False,0.0,435639.0,435639.0,0,False,True
94718,C,A,20080101,2008,52,2008,792,TUR,Türkiye,X,...,1976.0,False,0.0,False,0.0,17220.0,17220.0,0,False,True
94719,C,A,20080101,2008,52,2008,792,TUR,Türkiye,X,...,122.0,False,0.0,False,0.0,23909.0,23909.0,2,False,True
94720,C,A,20080101,2008,52,2008,792,TUR,Türkiye,X,...,31.0,False,0.0,False,0.0,323.0,323.0,0,False,True
94721,C,A,20080101,2008,52,2008,792,TUR,Türkiye,X,...,31.0,False,0.0,False,0.0,323.0,323.0,0,False,True

In [6]:
df3

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20090101,2009,52,2009,8,ALB,Albania,M,...,12042.000,False,NaN,False,337169.0,NaN,3.371690e+05,0,True,False
1,C,A,20090101,2009,52,2009,8,ALB,Albania,M,...,NaN,False,NaN,False,231.0,NaN,2.310000e+02,0,True,False
2,C,A,20090101,2009,52,2009,8,ALB,Albania,M,...,624.000,False,NaN,False,22809.0,NaN,2.280900e+04,0,True,False
3,C,A,20090101,2009,52,2009,8,ALB,Albania,M,...,220.000,False,NaN,False,1319.0,NaN,1.319000e+03,0,True,False
4,C,A,20090101,2009,52,2009,8,ALB,Albania,M,...,1.000,False,NaN,False,330.0,NaN,3.300000e+02,0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,C,A,20150101,2015,52,2015,276,DEU,Germany,X,...,141023.821,True,NaN,False,NaN,2.497329e+07,2.497329e+07,0,False,True
99996,C,A,20150101,2015,52,2015,276,DEU,Germany,X,...,8696.808,True,NaN,False,NaN,3.662769e+05,3.662769e+05,0,False,True
99997,C,A,20150101,2015,52,2015,276,DEU,Germany,X,...,109080.203,True,NaN,False,NaN,1.933991e+07,1.933991e+07,0,False,True
99998,C,A,20150101,2015,52,2015,276,DEU,Germany,X,...,502531.000,False,NaN,False,NaN,5.508773e+07,5.508773e+07,0,False,True
99999,C,A,20150101,2015,52,2015,276,DEU,Germany,X,...,74567.806,True,NaN,False,NaN,1.080810e+07,1.080810e+07,0,False,True

In [7]:
df4

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20180101,2018,52,2018,8,ALB,Albania,M,...,NaN,False,NaN,False,2050963.844,NaN,2.050964e+06,0,False,True
1,C,A,20180101,2018,52,2018,8,ALB,Albania,M,...,377951.86,False,NaN,False,1871234.484,NaN,1.871234e+06,0,False,True
2,C,A,20180101,2018,52,2018,8,ALB,Albania,M,...,3812.00,False,NaN,False,37787.493,NaN,3.778749e+04,0,False,True
3,C,A,20180101,2018,52,2018,8,ALB,Albania,M,...,NaN,False,NaN,False,11.893,NaN,1.189300e+01,0,False,True
4,C,A,20180101,2018,52,2018,8,ALB,Albania,M,...,NaN,False,NaN,False,141109.770,NaN,1.411098e+05,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49841,C,A,20190101,2019,52,2019,826,GBR,United Kingdom,X,...,22803.00,False,0.0,False,NaN,8.265099e+05,8.265099e+05,2,False,True
49842,C,A,20190101,2019,52,2019,826,GBR,United Kingdom,X,...,92794.00,False,0.0,False,NaN,8.526086e+06,8.526086e+06,2,False,True
49843,C,A,20190101,2019,52,2019,826,GBR,United Kingdom,X,...,144712.00,False,0.0,False,NaN,1.454076e+07,1.454076e+07,2,False,True
49844,C,A,20190101,2019,52,2019,894,ZMB,Zambia,X,...,NaN,False,0.0,False,NaN,7.233220e+04,7.233220e+04,0,False,True
49845,C,A,20190101,2019,52,2019,894,ZMB,Zambia,X,...,NaN,False,0.0,False,NaN,7.233220e+04,7.233220e+04,0,False,True

In [8]:
df5

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20200101,2020,52,2020,8,ALB,Albania,M,...,0.0,False,0.0,False,4924881.758,0.000,4924881.758,0,False,True
1,C,A,20200101,2020,52,2020,8,ALB,Albania,M,...,0.0,False,0.0,False,3822073.427,0.000,3822073.427,0,False,True
2,C,A,20200101,2020,52,2020,8,ALB,Albania,M,...,0.0,False,0.0,False,4895.275,0.000,4895.275,0,False,True
3,C,A,20200101,2020,52,2020,8,ALB,Albania,M,...,0.0,False,0.0,False,143875.494,0.000,143875.494,0,False,True
4,C,A,20200101,2020,52,2020,8,ALB,Albania,M,...,0.0,False,0.0,False,136478.444,0.000,136478.444,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48621,C,A,20210101,2021,52,2021,826,GBR,United Kingdom,X,...,1506.0,False,0.0,False,0.000,22163.082,22163.082,0,False,True
48622,C,A,20210101,2021,52,2021,894,ZMB,Zambia,X,...,4784.0,False,0.0,False,NaN,8976.036,8976.036,0,False,True
48623,C,A,20210101,2021,52,2021,894,ZMB,Zambia,X,...,3884.0,False,0.0,False,NaN,7179.318,7179.318,0,False,True
48624,C,A,20210101,2021,52,2021,894,ZMB,Zambia,X,...,150.0,False,0.0,False,NaN,485.736,485.736,0,False,True
48625,C,A,20210101,2021,52,2021,894,ZMB,Zambia,X,...,750.0,False,0.0,False,NaN,1310.982,1310.982,0,False,True

In [9]:
df6

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20220101,2022,52,2022,20,AND,Andorra,M,...,270307.86,False,0.0,False,1707871.590,NaN,1707871.590,0,False,True
1,C,A,20220101,2022,52,2022,20,AND,Andorra,M,...,94436.91,False,0.0,False,579854.875,NaN,579854.875,2,False,True
2,C,A,20220101,2022,52,2022,20,AND,Andorra,M,...,140.00,False,0.0,False,3815.271,NaN,3815.271,0,False,True
3,C,A,20220101,2022,52,2022,20,AND,Andorra,M,...,364.64,False,0.0,False,26177.982,NaN,26177.982,2,False,True
4,C,A,20220101,2022,52,2022,20,AND,Andorra,M,...,18000.00,False,0.0,False,112314.076,NaN,112314.076,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80051,C,A,20250101,2025,52,2025,826,GBR,United Kingdom,X,...,3584.00,False,0.0,False,NaN,568252.935,568252.935,2,False,True
80052,C,A,20250101,2025,52,2025,826,GBR,United Kingdom,X,...,3512.00,False,0.0,False,NaN,263897.033,263897.033,2,False,True
80053,C,A,20250101,2025,52,2025,826,GBR,United Kingdom,X,...,2.00,False,0.0,False,NaN,14762.544,14762.544,0,False,True
80054,C,A,20250101,2025,52,2025,826,GBR,United Kingdom,X,...,554.00,False,0.0,False,NaN,245612.080,245612.080,0,False,True
80055,C,A,20250101,2025,52,2025,826,GBR,United Kingdom,X,...,915.00,False,0.0,False,NaN,193443.510,193443.510,0,False,True

In [10]:
import pandas as pd

def format_columns(df: pd.DataFrame, rename_dict: dict = None, keep_columns: list = None) -> pd.DataFrame:
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(r"[^\w\s]", "", regex=True)
        .str.replace(" ", "_"))
    if rename_dict:
        df = df.rename(columns=rename_dict)
    if keep_columns:
        df = df[keep_columns]
    return df

rename_dict = {
    "refperiodid": "year",
    "reporteriso": "importer",
    "partneriso": "exporter",
    "flowcode": "flow",
    "cmdcode": "hs_code",
    "cmddesc": "product",
    "primaryvalue": "trade_value",
"motdesc": "transport"}

keep_columns = [
    "year",
    "importer",
    "flow",
    "exporter",
    "transport",
    "hs_code",
    "product",
    "trade_value"]

In [11]:
df1 = format_columns(df1, rename_dict, keep_columns)
df2 = format_columns(df2, rename_dict, keep_columns)
df3 = format_columns(df3, rename_dict, keep_columns)
df4 = format_columns(df4, rename_dict, keep_columns)
df5 = format_columns(df5, rename_dict, keep_columns)
df6 = format_columns(df6, rename_dict, keep_columns)

In [13]:
df6

,year,importer,flow,exporter,transport,hs_code,product,trade_value
0,20220101,AND,M,W00,TOTAL MOT,8541,"Semiconductor devices (e.g. diodes, transistor...",1707871.590
1,20220101,AND,M,CHN,TOTAL MOT,8541,"Semiconductor devices (e.g. diodes, transistor...",579854.875
2,20220101,AND,M,CZE,TOTAL MOT,8541,"Semiconductor devices (e.g. diodes, transistor...",3815.271
3,20220101,AND,M,FRA,TOTAL MOT,8541,"Semiconductor devices (e.g. diodes, transistor...",26177.982
4,20220101,AND,M,DEU,TOTAL MOT,8541,"Semiconductor devices (e.g. diodes, transistor...",112314.076
...,...,...,...,...,...,...,...,...
80051,20250101,GBR,X,TUR,Other,8541,"Semiconductor devices (e.g. diodes, transistor...",568252.935
80052,20250101,GBR,X,UKR,Other,8541,"Semiconductor devices (e.g. diodes, transistor...",263897.033
80053,20250101,GBR,X,MKD,Other,8541,"Semiconductor devices (e.g. diodes, transistor...",14762.544
80054,20250101,GBR,X,USA,Other,8541,"Semiconductor devices (e.g. diodes, transistor...",245612.080
80055,20250101,GBR,X,_X,Other,8541,"Semiconductor devices (e.g. diodes, transistor...",193443.510

In [14]:
datasets = {
    "Phase1": df1,
    "Phase2": df2,
    "Phase3": df3,
    "Phase4": df4,
    "Phase5": df5,
    "Phase6": df6
}

for name, df in datasets.items():
    print(f"\n===== {name} =====")
    
    for col in df.columns:
        print(f"\nColumn: {col}")
        print(df[col].value_counts().head())

===== Phase1 =====

Column: year
year
20010101    10168
20000101     9654
19990101     6692
19980101     6559
19970101     6149
Name: count, dtype: int64

Column: importer
importer
DEU    2489
CHE    2366
USA    2277
ESP    2136
SGP    1760
Name: count, dtype: int64

Column: flow
flow
M    35501
X    30408
Name: count, dtype: int64

Column: exporter
exporter
W00    2286
USA    1739
DEU    1652
GBR    1546
FRA    1460
Name: count, dtype: int64

Column: transport
transport
TOTAL MOT                                        62742
Air                                               1327
Road                                               644
Sea                                                463
Postal consignments, mail or courier shipment      332
Name: count, dtype: int64

Column: hs_code
hs_code
8541    65909
Name: count, dtype: int64

Column: product
product
Diodes, transistors, similar semiconductor devices; including photovoltaic cells assembled or not in modules, panels, light emitting mounted piezo-electric crystals    65909
Name: count, dtype: int64

Column: trade_value
trade_value
1000.0    343
2000.0    225
3000.0    156
4000.0    143
5000.0    105
Name: count, dtype: int64

===== Phase2 =====

Column: year
year
20080101    14040
20070101    12788
20060101    12569
20050101    11867
20040101    11846
Name: count, dtype: int64

Column: importer
importer
ESP    4782
CHE    4167
BRA    3281
TUR    2961
DEU    2809
Name: count, dtype: int64

Column: flow
flow
M    53394
X    41328
Name: count, dtype: int64

Column: exporter
exporter
W00    3209
USA    2331
DEU    2140
GBR    2006
CHN    1986
Name: count, dtype: int64

Column: transport
transport
TOTAL MOT    77568
Air           6725
Road          3373
Sea           2816
Other         2080
Name: count, dtype: int64

Column: hs_code
hs_code
8541    94722
Name: count, dtype: int64

Column: product
product
Diodes, transistors, similar semiconductor devices; including photovoltaic cells assembled or not in modules, panels, light emitting mounted piezo-electric crystals    94722
Name: count, dtype: int64

Column: trade_value
trade_value
1000.0    279
2000.0    167
1.0       143
3000.0    120
3.0        98
Name: count, dtype: int64

===== Phase3 =====

Column: year
year
20140101    17385
20130101    16528
20120101    15778
20110101    14708
20100101    14353
Name: count, dtype: int64

Column: importer
importer
DEU    6990
ESP    3641
BRA    3323
CHE    2680
ZAF    2429
Name: count, dtype: int64

Column: flow
flow
M    55292
X    44708
Name: count, dtype: int64

Column: exporter
exporter
W00    3063
USA    2171
CHN    2146
DEU    1904
GBR    1811
Name: count, dtype: int64

Column: transport
transport
TOTAL MOT                                        75847
Air                                               9727
Sea                                               5078
Road                                              4323
Postal consignments, mail or courier shipment     1917
Name: count, dtype: int64

Column: hs_code
hs_code
8541    100000
Name: count, dtype: int64

Column: product
product
Diodes, transistors, similar semiconductor devices; including photovoltaic cells assembled or not in modules, panels, light emitting mounted piezo-electric crystals    100000
Name: count, dtype: int64

Column: trade_value
trade_value
1.0       115
1000.0     98
2.0        76
3.0        73
6.0        72
Name: count, dtype: int64

===== Phase4 =====

Column: year
year
20180101    25226
20190101    24620
Name: count, dtype: int64

Column: importer
importer
DEU    1926
FRA    1720
ESP    1367
CAN    1346
CZE    1205
Name: count, dtype: int64

Column: flow
flow
M    28294
X    21552
Name: count, dtype: int64

Column: exporter
exporter
W00    1670
CHN    1165
USA    1097
DEU    1035
FRA     914
Name: count, dtype: int64

Column: transport
transport
TOTAL MOT    26517
Air           8983
Road          5053
Sea           4044
Other         1945
Name: count, dtype: int64

Column: hs_code
hs_code
8541    49846
Name: count, dtype: int64

Column: product
product
Diodes, transistors, similar semiconductor devices; including photovoltaic cells assembled or not in modules or panels, light-emitting diodes (LED), mounted piezo-electric crystals    45953
Diodes, transistors, similar semiconductor devices; including photovoltaic cells assembled or not in modules, panels, light emitting mounted piezo-electric crystals                     3893
Name: count, dtype: int64

Column: trade_value
trade_value
100.000     28
105.727     23
1000.000    22
1.000       22
300.000     21
Name: count, dtype: int64

===== Phase5 =====

Column: year
year
20210101    24884
20200101    23742
Name: count, dtype: int64

Column: importer
importer
DEU    1902
FRA    1778
ESP    1329
CAN    1312
TUR    1274
Name: count, dtype: int64

Column: flow
flow
M    27276
X    21350
Name: count, dtype: int64

Column: exporter
exporter
W00    1602
CHN    1146
USA    1054
DEU     994
GBR     899
Name: count, dtype: int64

Column: transport
transport
TOTAL MOT    26198
Air           8651
Road          5043
Sea           3896
Other         1481
Name: count, dtype: int64

Column: hs_code
hs_code
8541    48626
Name: count, dtype: int64

Column: product
product
Diodes, transistors, similar semiconductor devices; including photovoltaic cells assembled or not in modules or panels, light-emitting diodes (LED), mounted piezo-electric crystals    46922
Diodes, transistors, similar semiconductor devices; including photovoltaic cells assembled or not in modules, panels, light emitting mounted piezo-electric crystals                     1704
Name: count, dtype: int64

Column: trade_value
trade_value
116.597     33
200.000     26
1000.000    25
1.000       23
3000.000    20
Name: count, dtype: int64

===== Phase6 =====

Column: year
year
20230101    24776
20220101    24337
20240101    23159
20250101     7784
Name: count, dtype: int64

Column: importer
importer
DEU    2929
FRA    2844
GBR    2701
CZE    2360
MYS    2034
Name: count, dtype: int64

Column: flow
flow
M    43810
X    36246
Name: count, dtype: int64

Column: exporter
exporter
W00    2438
CHN    1785
USA    1656
DEU    1543
GBR    1387
Name: count, dtype: int64

Column: transport
transport
TOTAL MOT                                        42176
Air                                              14511
Road                                              8286
Sea                                               6729
Postal consignments, mail or courier shipment     2615
Name: count, dtype: int64

Column: hs_code
hs_code
8541    80056
Name: count, dtype: int64

Column: product
product
Semiconductor devices (e.g. diodes, transistors, semiconductor based transducers); including photovoltaic cells assembled or not in modules or panels, light-emitting diodes (LED) assembled with other LEDs or not, mounted piezo-electric crystals    75612
Diodes, transistors, similar semiconductor devices; including photovoltaic cells assembled or not in modules or panels, light-emitting diodes (LED), mounted piezo-electric crystals                                                                     3641
Diodes, transistors, similar semiconductor devices; including photovoltaic cells assembled or not in modules, panels, light emitting mounted piezo-electric crystals                                                                                      803
Name: count, dtype: int64

Column: trade_value
trade_value
1000.00    38
98.87      32
20.00      27
5.00       27
10.00      26
Name: count, dtype: int64

In [15]:
df1["product"] = "semiconductor devices"
df2["product"] = "semiconductor devices"
df3["product"] = "semiconductor devices"
df4["product"] = "semiconductor devices"
df5["product"] = "semiconductor devices"
df6["product"] = "semiconductor devices"

In [25]:
def check_null(df):
    nulls = df.isna().sum()
    percent = (nulls / len(df)) * 100
    return pd.DataFrame({
        "missing_values": nulls,
        "percent_missing": percent})

print(check_null(df1))
print(check_null(df2))
print(check_null(df3))
print(check_null(df4))
print(check_null(df5))
print(check_null(df6))

             missing_values  percent_missing
year                      0              0.0
importer                  0              0.0
flow                      0              0.0
exporter                  0              0.0
transport                 0              0.0
hs_code                   0              0.0
product                   0              0.0
trade_value               0              0.0
             missing_values  percent_missing
year                      0              0.0
importer                  0              0.0
flow                      0              0.0
exporter                  0              0.0
transport                 0              0.0
hs_code                   0              0.0
product                   0              0.0
trade_value               0              0.0
             missing_values  percent_missing
year                      0              0.0
importer                  0              0.0
flow                      0              0.0
exporter                  0              0.0
transport                 0              0.0
hs_code                   0              0.0
product                   0              0.0
trade_value               0              0.0
             missing_values  percent_missing
year                      0              0.0
importer                  0              0.0
flow                      0              0.0
exporter                  0              0.0
transport                 0              0.0
hs_code                   0              0.0
product                   0              0.0
trade_value               0              0.0
             missing_values  percent_missing
year                      0              0.0
importer                  0              0.0
flow                      0              0.0
exporter                  0              0.0
transport                 0              0.0
hs_code                   0              0.0
product                   0              0.0
trade_value               0              0.0
             missing_values  percent_missing
year                      0              0.0
importer                  0              0.0
flow                      0              0.0
exporter                  0              0.0
transport                 0              0.0
hs_code                   0              0.0
product                   0              0.0
trade_value               0              0.0

In [22]:
check_null(df6)

             missing_values  percent_missing
year                      0              0.0
importer                  0              0.0
flow                      0              0.0
exporter                  0              0.0
transport                 0              0.0
hs_code                   0              0.0
product                   0              0.0
trade_value               0              0.0